- name: Install zfs_autobackup
  hosts: myhosts
  tasks:
  - name: Install pipx
    apt:
      name: pipx
  - name: Install zfs_autobackup
    community.general.pipx:
      name: zfs-autobackup
  - name: Set path in profile
    lineinfile:
      dest: ~root/.bashrc
      insertafter: EOF
      line: "export PATH=$PATH:/root/.local/bin"
  - name: Create hourly backup job
    ansible.builtin.cron:
      name: "hourly zfs-autobackup"
      special_time: hourly
      # Have to escape "%" otherwise cron will take it as a newline - https://en.wikipedia.org/wiki/Cron
      job: bash -c '/root/.local/bin/zfs-autobackup -v main --keep-source=1h1d,1d1w,1w1m,1m1y,1y1000y --snapshot-format "{}-\%Y-\%m-\%dT\%H:\%M:\%S" 2>&1 | logger -t zfs-autobackup'
  - name: Restart cron
    service:
      name: cron
      state: restarted
